name: CI - Format with Google Java Format
permissions:
  contents: write

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event_name == 'push' && github.ref || github.head_ref }}
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--replace"
          commit-message: "style(ci): format"
          github-token: ${{ secrets.GITHUB_TOKEN }}
